### PR TITLE
Upgrade Go runtime to version 1.5.3

### PR DESCRIPTION
**Pull request by mattbostock**
So that we don't lag behind recent versions and to take advantage of
this security fix in version 1.5.3:

https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4

I've removed the `GOMAXPROCS` option as Go 1.5 uses all available CPUs
by default (previously it defaulted to 1 CPU) and there's no good reason
for us not to use all CPUs:

https://golang.org/doc/go1.5

Due to the Go language compatibility promise I don't think there are
any other changes in Go 1.5 likely to affect this app:
https://golang.org/doc/go1compat

Also, fix dependencies which were no longer available so that the build can complete successfully. 
As it's difficult to verify these changes easily (since we're not vendoring our code), I'm relying on our tests to verify that nothing has broken. Please see the commit messages for more details.

### CODE REVIEW

**Comment by boffbowsh** [comment]
LGTM, but I am not a go-nut. Can we run this in integration at all?

**Comment by mattbostock** [comment]
@boffbowsh It does run in Integration, so we could just deploy it there and see what it does before deploying to Production.

**Comment by mattbostock** [comment]
@boffbowsh To be clear, I've not vetted all of the dependency changes thoroughly but if the tests pass and it runs well in Integration, I think it's fine to go to Production. The tests are pretty comprehensive.

**Comment by deanwilson** [comment]
It's worth an effort. Merge away.

**Pull request merged**
