### PR TITLE
Move to Godep for dependency management

### PR DESCRIPTION
**Pull request by timblair**

### CODE REVIEW

**Comment by gpeng** [comment]
:+1:

**Comment by alexmuller** [comment]
Are we keeping 20,000 lines of vendored code in the repo?

**Comment by timblair** [comment]
@alexmuller: we are.

Vendoring like this is currently seen as best practice for Go development.  It means we're not susceptible to a [left-pad situation](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/), and that we don't need to rely on any extra tooling (like [Gom](https://github.com/mattn/gom)) on the build server: recent versions of Go (>= 1.5) have built-in support for finding dependencies in the `vendor/` directory.

We've already shifted both alphagov/router#108 and alphagov/metadata-api#23 to use this approach.

There's an ongoing, official attempt to [come up with a blessed packaging approach](https://docs.google.com/document/d/1M4Ldgtxr9vC8wpyTldQe5oUyGN9eb1CeUcJT3N5XaPk/edit), which currently favours a manifest + lockfile approach (similar to `Gemfile` and `Gemfile.lock`), but my assumption is that this is a standardisation of the _management_ of dependency versions, and the preference will still be to vendor.

I'm on the fence about the costs/benefits of vendoring, but I think that we're best to stick to this approach, at least until the above process has made some headway and there's some standard (built-in, or "approved") tooling around dependency management.

**Comment by alexmuller** [comment]
Cool, thanks for explaining!

**Pull request merged**
